# Express will catch your synchronous errors, to prevent server chrashing

THIS IS WHAT EXPRESS DOES FOR YOU, IF YOU WOULD THROW AN ERROR IN NORMAL NODEJS SERVER, IT WOULD CRACH LIKE ANY OTHER NODEJS APP, NO MATTER YOU HAVE SERVER OR NOT

```ts
app.get("/hello-world", (req, res) => {
  throw new Error("Hello World Error!");
});
```

SEND A RQUEST WITH HTTPIE:

```
http :3001/hello-world
```

OR WITH SOME HTTP CLIENT LIKE THUNDER CLIENT

**YOU WILL GET HTML BACK; WITH STACK TRACE OF THE ERROR THEN WAS THROWN** (**LIKE I SAID THIS IS ONLY POSSIBLE WITH **)
(POSSIBLE ONLY IF YOU HAVE 'NORMAL' FUNCTION (IF YOU WOULD PUT `async/await` SERVER WOULD CRACH AND YOU WOULDN'T GET HTML WITH ERROR STACK TRACE) AND YOU WOULD HAVE TO RESTART YOUR SERVER

SO, IN CASE OF SYNC ERRORS, EXPRESS IS CATCHING YOUR ERROR, AN ERROR THAT YOU DIDN'T CATCH BY YOURSELF AND IT IS SENDING RESPONSE WITH 500 STATUS AND SOME HTML

WE DON'T WANT TO SEND THAT STUFF TO THE USER; WE NEED TO HANDLE EVERYTHING WE CAN

# DEFINING YOUR OWN ERROR HANDLER

THE DIFFERENCE BETWEEN THIS ONE IS THAT ERROR HANDLER HAS 4 ARGUMENTS: `error`, `req`, `res`, `next`

FIRT ARGUMENT IS ERROR THAT WAS THROWN

THIS HANDLER CAN DO THINGS LIKE ANY HANDLER OR A MIDDLEWARE, ONLY DIFFERENCE IS WHERE YOU PUT IT

IT NEEDS TO COME AFTER ALL THE ROUTS IF YOU WANT TO CATCH ERRORS FROM THESE ROUTES

```ts
// REMMBER THAT THIS WILL NOT CATCH ERROR IF ERROR IS THROWN FROM async

app.use((err: Error, req: Request, res: Response, next: NextFunction) => {
  //
  //
  console.log({ err: err.message });

  res.json({ message: "oooooooooooops" });
});
```


# NOTHING STOPS YOU TO USE ASYNCHRONOUS THINGS INSIDE ERROR HANDLER

I ONLY TOLD YOU THAT YOU CAN'T JUST THROW ERROR INSIDE ASYNC HANDLER AND EXPECT ERROR HANDLER TO CATCH THAT ERROR

**BUT YOU CAN DO ASYNC THINGS INSIDE ERROR HANDLER** (ADDING INSTRUMENTATION, ERROR LOGING, ERROR REPORTING...)

# SO TO CEMENT KNOWLEDGE ABOUT ERROR HANDLER NOT BEING ABLE TO CATCH ERROR FROM ASYNC HANDLER, OR FROM ANY ASYNC ACTION, LETS DEFINE TWO HANDLERS

```ts
// -----------------------------
// IF YOU HIT THIS ROUTE, SERVER WILL CHRACH
app.get("/hello-world", async (req, res) => {
  throw new Error("Hello World Error!");
});
// IF YOU HIT THIS ROUTE, SERVER WILL CHRACH
app.get("/foo-bar", (req, res) => {
  setTimeout(() => {
    throw new Error("Foo Bar!");
  }, 200);
});



// 
// 
// 
// 

app.use((err: Error, req: Request, res: Response, next: NextFunction) => {
  //
  //
  console.log({ err: err.message });

  res.json({ message: "oooooooooooops" });
});
```

# ASYNCRONOUS ERRORS YOU MUST HANDLE BY YOURSELD ON A HANDLER LEVEL, BY USING `next` CALLBACK, BECAUSE SAME AS MIDDLEWARES, THE HANDLERS ALSO CAN HAVE A `next` PARAMETER

**YOU CAN LOOK AT NEXT AS A THING THAT WWILL TRANSPORT ERROR FROM HANDLER OR A MIDDLEWARW, TO THE ERROR HANDLER**

AS A MATTER OF FCT, IF YOU PASS ANYTHING TO NEXT, IT WILL BE TREATED AS AN ERROR

SO, IN CASE OF THIS EXAMPLES ERROR WILL BE "TRASPORTED" TO THE ERROR HANDLER

```ts
// THIS TIME ERROR IS BING PASSED TO next
app.get("/hello-world", async (req, res, next) => {
  next(new Error("Hello World Error!"));
});
// ALSO IN THIS ROUTE I ALSO PASSED ERROR TO THE next
app.get("/foo-bar", (req, res, next) => {
  setTimeout(() => {
    next(new Error("Foo Bar!"));
  }, 200);
});

// 
// 
// 
// 
// 
// 
// 

app.use((err: Error, req: Request, res: Response, next: NextFunction) => {
  //
  //
  console.log({ err: err.message });

  res.json({ message: "oooooooooooops" });
});
```

NOW IT WILL WORK, ERROR WILL BE PASSED TO ERROR HANDLER

TESTIT WIT HTTPIE

```
http :3001/hello-world
```

```
http :3001/foo-bar 
```

OR OPEN LINK IN BROWSER SINCE WE ARE DOING GET REQUEST

# HANDLER FOR SUB ROUTER (FOR ANY OF ROUTERS WE USE)

```ts
// BUT REMEMBER THAT THIS HANDLER DOESN'T BELONG TO ANY
// SUB ROUTES (THIS IS OUR ERROR HANDLER IN `src/server.ts`)
// FOR SUB ROUTER WE NEED TO DEFINE NEW HANDLER

app.use(
  (
    err: Error & { type: string },
    req: Request,
    res: Response,
    next: NextFunction
  ) => {
    // WE WILL BE PSSING TYPE TOGETHER WITH ERROR WHEN
    // WE HANDLE ERRORS

    if (err.type === "auth") {
      res.status(401).json({ errors: [{ message: "Unauthorized!" }] });
      return;
    } else if (err.type === "input") {
      res.status(401).json({ errors: [{ message: "Invalid input!" }] });
      return;
    } else {
      res.status(500).json({ errors: [{ message: "Oooooops, our bad!" }] });
      return;
    }
  }
);
```

**THIS WILL WORK FOR SUB ROUTER (OUR ALL ROUTES THAT START WITH /api/)**

```
src/router.ts
```

```ts
router.use(
  (
    err: Error & { type: string },
    req: Request,
    res: Response,
    next: NextFunction
  ) => {
    if (err.type === "auth") {
      res.status(401).json({ errors: [{ message: "Unauthorized!" }] });
      return;
    } else if (err.type === "input") {
      res.status(401).json({ errors: [{ message: "Invalid input!" }] });
      return;
    } else {
      res.status(500).json({ errors: [{ message: "Oooooops, our bad!" }] });
      return;
    }
  }
);

```
